### PR TITLE
Replace new arm64 APKs for docs, sheets, slides, maps, play games, earth

### PR DESCRIPTION
**Pull request by mc1100**

### CODE REVIEW

**Comment by mfonville** [comment]
thanks, where did you get these APKs?

**Comment by mc1100** [comment]
They were pulled from my Elephone G2 phone after the were updated from
Google Play.

2015-06-22 20:33 GMT+02:00 mfonville <notifications@github.com>:

**Comment by mfonville** [comment]
Ok, if you are interested in helping with keeping the arm64 packages updated, you could try to install this chrome extension: https://lekensteyn.nl/apk-downloader/
Then you can just download the APKs with your browser, if you fill in the Android GSF ID (the Play Services ID) of your phone. It should be more easy then downloading on the phone, and then transferring.
I really need someone with an arm64 device who can do this for the team (since I lack myself an arm64 device).

I also still need better/more reliable arm64 sources for e.g. Google Wallet, Google Sound Search (from this commit https://github.com/opengapps/arm64/commit/f0c1d75c565ddf7bf0d646178bbfd0f0bbcc1301 ), because I got those currently by extracting them from the Volantis 9 image, but had to de-odex (with which I have no experience at all) and are probably currently in a very broken state.

**Comment by mc1100** [comment]
Unfortunately, APK Downloader does not work for me (authentication error).
Anyway, Google Play says none of my devices is compatible with the Google
Sound Search. None of my devices have NFC and therefore I cannot download
Google Wallet as well. :( I am expecting a new arm64 device from China, so
I may try with that one as soon as it arrives.

2015-06-22 21:20 GMT+02:00 mfonville <notifications@github.com>:

> Android GSF ID

**Comment by mfonville** [comment]
How weird that you get this authentication error. Maybe you have to set this: https://www.google.com/settings/security/lesssecureapps ?

**Comment by mfonville** [comment]
Could you still have a lookt at this, if you'd have the time? I am especially missing Google Movies at the moment.

**Comment by NicholasBuse** [comment]
It could be two-step auth issue too. I think that is my issue with the
tool. I was going to setup a junk Gmail account without two-step enabled to
see if that fixes my auth issues. I'll report back.

**Comment by mfonville** [comment]
For two-step authentication you need to generate an app-specific password anyhow (that is what I have done), at: https://security.google.com/settings/security/apppasswords

**Comment by mc1100** [comment]
I have 2-step auth enabled and of course I did create app-specific
password. Just did it again few seconds ago. And again no luck, I got
"ERROR: Authentication token not available, cannot login." message. I could
not use *#*#TALK#*#* technique for getting my device ID. I used this app
instead: https://play.google.com/store/apps/details?id=com.evozi.deviceid.
Could you confirm it gives good ID for you?

Regarding the Google Movies, there is no update for my device at the moment
in Google Play Market. But as soon as there are any, I can provide it to
the open gapps project.

2015-06-25 8:57 GMT+02:00 mfonville <notifications@github.com>:

**Comment by mfonville** [comment]
If you used the GSF generated by that application it should work.

**Comment by mfonville** [comment]
Btw, I will just add you to the 'Packagers' team, then when updates are available, you can directly push them to the repository.

**Comment by mc1100** [comment]
OK, thanks.

2015-06-25 10:02 GMT+02:00 mfonville <notifications@github.com>:

**Comment by mfonville** [comment]
lol, I did log out of the extension, and now I can't login anymore, I got the very same error. I guess Google did change something on their end...

**Comment by NicholasBuse** [comment]
I tried again this morning (using app-specific passworkd) and still had the auth error...

**Comment by mc1100** [comment]
This one seems to be working:
https://chrome.google.com/webstore/detail/apk-downloader/cgihflhdpokeobcfimliamffejfnmfii/related?hl=en&gl=VN
.

2015-06-25 18:32 GMT+02:00 mfonville <notifications@github.com>:

**Comment by mfonville** [comment]
OK, now using that other extension, good find :-)
In the meantime I installed android-x86 in my KVM/QEMU emulator, so I now have a device ID for x86 apps, so I can add those soon :)

**Comment by oRAirwolf** [comment]
I just ripped all of the GApps off of the play store and PM'd mfonville thru XDA with a Dropbox link.  Let me know if there is anything else I can do.

**Comment by mfonville** [comment]
Super! I am downloading the package from Dropbox now, and will upload any apps that are missing/old to the repo! :)

It is so great so see so many people contribute :-) (makes me really happy)

**Comment by oRAirwolf** [comment]
Feel free to shoot me a PM any time if you need me to grab updated GApps or if there is anything I can do.  I absolutely love these open GApps and love contributing!

**Pull request merged**
